const locations = [
{ name: "Doda", lat: 33.1449, lng: 75.5472 },
{ name: "Jammu", lat: 32.7266, lng: 74.8570 },
{ name: "Kathua", lat: 32.3721, lng: 75.5122 },
{ name: "Kishtwar", lat: 33.3152, lng: 75.7669 },
{ name: "Poonch", lat: 33.7725, lng: 74.0882 },
{ name: "Rajouri", lat: 33.3811, lng: 74.3142 },
{ name: "Ramban", lat: 33.2451, lng: 75.1946 },
{ name: "Reasi", lat: 33.0822, lng: 74.8357 },
{ name: "Samba", lat: 32.5569, lng: 74.8664 },
{ name: "Udhampur", lat: 32.9252, lng: 75.1375 },
{ name: "Anantnag", lat: 33.7315, lng: 75.1443 },
{ name: "Bandipora", lat: 34.4700, lng: 74.5742 },
{ name: "Baramulla", lat: 34.2095, lng: 74.3436 },
{ name: "Budgam", lat: 34.2703, lng: 74.7726 },
{ name: "Ganderbal", lat: 34.2703, lng: 74.7726 },
{ name: "kulgam", lat: 32.5569, lng: 74.8664 },
{ name: "Kupwara", lat: 34.5270, lng: 74.2615 },
{ name: "Pulwama", lat: 33.8782, lng: 74.8928 },
{ name: "Shopian", lat: 33.7144, lng: 74.7973 },
{ name: "Srinagar", lat: 34.0837, lng: 74.7973 },
{ name: "Kargil", lat: 34.5631, lng: 76.1347 },
{ name: "Leh", lat: 34.1646, lng: 77.5848 }



]